### ISSUE TITLE
Wordle rule subtle difference

### ISSUE THREAD

**Issue by mbleigh** [mbleigh/pictle#10]
In Wordle if there's only one of a given letter, a second one will show up as gray not yellow/green. This is not the case currently in Pictle. Consider making the rules match.

**Comment by sensei1024** [comment]
Similarly, if the word is LACES, and the guess is CACHE, there should be one green C.

Pictle scores this as one yellow C and one green C.

**Comment by YellowSkarmory** [comment]
This screwed me over on my first time playing – had to use a gimme on one because I couldn't think of anything that used all 5 letters for today's second row.

**Comment by mbleigh** [comment]
I have just pushed an update that uses the same colorings as Wordle for repeating letters. The changes from before are:

1. If a letter is already guessed in the correct spot (even later in the word), its use elsewhere will be blank, not yellow.
2. If multiple of the same letter are used, they will only be yellow until the number of letters in the word are used up, then they'll be blank.

This matches Wordle's behavior, which is better, but also has the side effect of making the game even more challenging - especially for getting unique word scores.
