### ISSUE TITLE
Gimme won't work for last row

### ISSUE THREAD

**Issue by ray-monde-92** [mbleigh/pictle#18]
Got stuck on last row (for Pictle 239) and wanted to use a gimme for it; after clicking, it doesn't seem to give an answer and the game freezes. Not sure if it's because there's an issue with the gimme feature or if that's because there's no word that matches the pattern.

**Comment by shakeel** [comment]
The picture pattern for puzzle #239 has no matching words in the American English dictionary.

`grep "^[obin][^robin]b[^robin][robi]$" /usr/share/dict/american-english`

**Comment by mbleigh** [comment]
Puzzle 239 was...not great. Something seems to have gone wrong and both the letter score and the calculated valid words were somehow off. I think the reason the gimme didn't work is that there weren't any "guessable words" that could fill that slot. Not sure how that happened exactly, but it shouldn't recur unless I screw up another puzzle. Sorry about that!
